version: "3"

volumes:
  webroot:
    driver: local

services:
  web:
    build:
      context: ../../
      dockerfile: docker/release/Dockerfile
    image: dotrollen/devblog:latest
    depends_on: 
      - mongodb
    volumes:
      - webroot:/var/www/devblog
    env_file: ../../.env
    ports:
      - "5000:5000"

  nginx:
      build: 
        context: .
        dockerfile: Dockerfile.nginx
      depends_on:
        - web
        - mongodb
      ports:
        - "8000:8000"
      volumes:
        - webroot:/var/www/devblog
    
  mongodb:
    image: mongo:4.0.0
    restart: always
    env_file: ../../.env